added question pages
devcenter-square/coding101 pull request #10
Opened 2017-07-17 17:57 UTC by armydar

2017-07-18 19:43 UTC, abiodun0 commented
@armydar Can you update this PR with screen shots?

2017-07-18 20:35 UTC, armydar commented
good evening... please i don't understand the question.

On Tue, Jul 18, 2017 at 8:43 PM, Abiodun Shuaib <notifications@github.com>
wrote:

> Closed #10 <https://github.com/devcenter-square/coding101/pull/10>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/devcenter-square/coding101/pull/10#event-1169015116>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVkb4Dd3Py9VyxCWRWBHpm7Ru92XFx_eks5sPQrGgaJpZM4OaUmx>
> .
>

2017-07-18 21:56 UTC, armydar commented
![Uploading screengrab.PNG…](index.html)

2017-07-18 22:03 UTC, armydar commented
![begin](https://user-images.githubusercontent.com/22617056/28341796-0a8d8382-6c0d-11e7-9a5b-4fabbc9db684.PNG)
![question 1](https://user-images.githubusercontent.com/22617056/28341810-210107a6-6c0d-11e7-8506-8df2d7476f74.PNG)
![question 2](https://user-images.githubusercontent.com/22617056/28341819-2b245e2c-6c0d-11e7-9c86-d6ebb57fbc70.PNG)
![question 3](https://user-images.githubusercontent.com/22617056/28341831-39b2ff8e-6c0d-11e7-8c30-aa87e5cf7e34.PNG)

2017-07-18 22:05 UTC, armydar commented
![screengrab](https://user-images.githubusercontent.com/22617056/28341888-870a17b8-6c0d-11e7-89d7-3e37c1d0552b.PNG)

2017-07-19 10:29 UTC, abiodun0 requested changes
The logo as it appears seems too big. This should be made to be a regular navigation local like in popular websites. You can use devcenter.co as a guide when doing this.

Overall Good job. But this seem to be designed without atheistic and making it visually appealing in mind. Please put this into consideration when implementing the feedbacks. add a css file or use a css framework will be a +

2017-07-19 10:29 UTC, abiodun0 commented on begin.html
> +<head>
***Code Quality: Critical***
This seems to be designed without any use of css or care for responsiveness. This should be refactored and appropriate css should be used.

2017-07-19 10:29 UTC, abiodun0 commented on begin.html
> +  <section>
***Code Quality: Nitpick***
This should be revisited and divided into reasonable divs

2017-07-19 12:02 UTC, osioke commented
@abiodun0 this PR addresses just the HTML pages, in the next task she is to add the CSS files, and beautify it.

@armydah to help with this, on your next PR, mention the issue no you are solving with the PR, so anyone reviewing will remember what the task is. So

2017-07-19 16:24 UTC, abiodun0 commented
@osioke Awesome .. those this means i can merge this request?

2017-07-19 17:13 UTC, armydar commented on begin.html
> +<head>
yes...no  styling as the #4 is basically to create plain html

2017-07-19 17:35 UTC, osioke commented
At all @abiodun0, she still has to do the landing page, group all the front-end work in a folder on the repo, link the pages, add the image folder,  and redo the template page for the questions and resource. cc: @armydah

2017-07-23 21:30 UTC, armydar commented
fixed issue  #5  @abiodun0

2017-07-24 21:26 UTC, merged