frontend task #4 @theo4u
devcenter-square/coding101 pull request #13
Opened 2017-08-18 10:05 UTC by clux2605

Corrections to the folder structure

2017-08-18 13:06 UTC, osioke commented
@clux2605 you did the SVG logo yourself?

2017-08-18 20:21 UTC, theo4u commented on frontend/category.html
> +			<img src="res/devcenter-logo.svg">
not found, no **res** folder instead `assets/img/`

2017-08-18 20:24 UTC, theo4u commented on frontend/explainer.html
> +		<button type="button" href="category.html">Begin</button>
this should be a link, `<a href="category.html">Begin</a>`

2017-08-18 20:25 UTC, theo4u commented on frontend/index.html
> +		<button type="button" href="explainer.html">How?</button>
same as above, use link

2017-08-18 20:25 UTC, theo4u commented on frontend/index.html
> +			<img src="res/devcenter-logo.svg">
resource not found

2017-08-18 20:28 UTC, theo4u commented on frontend/question.html
> +				        <input type="checkbox" name="question-1-answers" id="question-1-answers-A" value="A" />
the checkbox should be radio button as you can only pick one answer per question

2017-08-18 20:32 UTC, theo4u commented
check the comments placed on changed files, and no **result** page #4 last image

2017-08-18 20:35 UTC, theoomoregbee requested changes
1. Check your src to devcenter svg
2. No Result page
3. Use link instead of button(and buttons don't use href)

2017-08-19 03:06 UTC, clux2605 commented on frontend/category.html
> +			<img src="res/devcenter-logo.svg">
oh, my bad, forgot to change the dir when i changed the folder structure.

2017-08-19 11:28 UTC, theoomoregbee requested changes

2017-08-19 11:28 UTC, theo4u commented on frontend/index.html
> +        <a href="./">
no need for thr link here, anyway `href` should be **#** instead

2017-08-19 11:28 UTC, theo4u commented on frontend/index.html
> +        <a href="explainer.html"></a>
no link Text

2017-08-19 11:28 UTC, theo4u commented on frontend/explainer.html
> +        <a href="category.html"></a>
no link text

2017-08-19 19:50 UTC, clux2605 commented on frontend/explainer.html
> +        <a href="category.html"></a>
corrected

2017-08-20 11:35 UTC, theoomoregbee approved these changes
well done 👏

2017-08-20 11:36 UTC, merged